### ISSUE TITLE
No more disposable domains policy

### ISSUE THREAD

**Issue by bago** [andreis/disposable#31]
What's your policy with domains that are no more used for DEA services?

Most domains in the list don't even have an MX or A record or they don't exists anymore or they don't provide any nameserver, so they can't anymore be disposable email address. At most, they are dead addresses.

Some other domain is alive, but I'm mosty sure they have been disposable years ago and they are now not anymore disposable.

So, my question: are these domains listed "by design" or are they listed "by mistake"?

**Comment by andreis** [comment]
This is nothing more than a glorified hash table, obtained by composing various existing sources.

"Dead" domains don't affect this tool that much, but we can remove them if either:
- the domains are provably dead
- the domains are now provably used for other "legitimate" purposes (the legitimacy of disposable email services is debatable, I for one don't mind them and use 10minutemail frequently)

**Comment by smeinecke** [comment]
@bago this is somehow by design. For example: 
I don't use the list as "live" tool to verify if the user who wants to create an account uses a temporary email address - I use this list to check which users / email adresses in my database are probably "invalid" and should not get any emails or should be deactivated - so I need all disabled / old domains too :)

But, there is a parameter in the generator to verify if the domains DNS Zone has a MX record. (`--dns-verify`).

**Comment by bago** [comment]
Thank you for your answers! of course there is no "right thing", it's just a choice/policy, so I wanted to check!

disposable domains often are very volatile and sometimes they are driven by spamtrap networks: first they offer some disposable service, then they return "no such inbox" for 1 year, then turn them into spamtraps.

given many services are able to block DEA domains, many users uses gmail.com or mail.ru for their disposable operations nowadays :-( it's an eternal fight...

**Comment by smeinecke** [comment]
Since we will move the "cached" files from this repository to a separate repository which will be automatically updated daily, I will add a separate list for MX tested domains.
